/*
  Avtogeneratsiya: npm run crm:seed-sql
  Pozitsii praysa iz lib/service-details.ts
  cost_usd: orientiry publichnyh USD (scripts/catalog-cost-usd.mjs) — ne vasha zakupka.
*/

INSERT INTO public.crm_services (category_id, name, catalog_key, line_type, cost_usd, default_markup_percent, sort_order)
SELECT c.id, v.name, v.catalog_key, v.line_type::public.crm_deal_line_type, v.cost_usd::numeric, v.markup::numeric, v.ord
FROM public.crm_service_categories c
JOIN (VALUES
  (1, 'ai'::text, 'Suno'::text, 'suno'::text, 'subscription'::text, 10::numeric, 15::numeric),
  (2, 'ai'::text, 'Midjourney'::text, 'midjourney'::text, 'subscription'::text, 10::numeric, 15::numeric),
  (3, 'ai'::text, 'Gamma'::text, 'gamma'::text, 'subscription'::text, 18::numeric, 15::numeric),
  (4, 'ai'::text, 'DeepSeek'::text, 'deepseek'::text, 'subscription'::text, 10::numeric, 15::numeric),
  (5, 'ai'::text, 'Cursor'::text, 'cursor'::text, 'subscription'::text, 20::numeric, 15::numeric),
  (6, 'ai'::text, 'Krea'::text, 'krea'::text, 'subscription'::text, 18::numeric, 15::numeric),
  (7, 'ai'::text, 'OpenAI API'::text, 'openai_api'::text, 'subscription'::text, 0::numeric, 15::numeric),
  (8, 'ai'::text, 'Kling'::text, 'kling'::text, 'subscription'::text, 15::numeric, 15::numeric),
  (9, 'ai'::text, 'Runway'::text, 'runway'::text, 'subscription'::text, 25::numeric, 15::numeric),
  (10, 'ai'::text, 'ElevenLabs'::text, 'elevenlabs'::text, 'subscription'::text, 22::numeric, 15::numeric),
  (11, 'ai'::text, 'Freepik'::text, 'freepik'::text, 'subscription'::text, 12::numeric, 15::numeric),
  (12, 'ai'::text, 'Lensa'::text, 'lensa'::text, 'subscription'::text, 8::numeric, 15::numeric),
  (13, 'ai'::text, 'Perplexity'::text, 'perplexity'::text, 'subscription'::text, 20::numeric, 15::numeric),
  (14, 'ai'::text, 'Grok'::text, 'grok'::text, 'subscription'::text, 10::numeric, 15::numeric),
  (15, 'ai'::text, 'Candy AI'::text, 'candy'::text, 'subscription'::text, 15::numeric, 15::numeric),
  (16, 'ai'::text, 'Leonardo AI'::text, 'leonardo'::text, 'subscription'::text, 15::numeric, 15::numeric),
  (17, 'ai'::text, 'Pika'::text, 'pika'::text, 'subscription'::text, 15::numeric, 15::numeric),
  (18, 'ai'::text, 'NanoBanana'::text, 'nanobanana'::text, 'subscription'::text, 10::numeric, 15::numeric),
  (19, 'ai'::text, 'Claude'::text, 'claude'::text, 'subscription'::text, 20::numeric, 15::numeric),
  (20, 'ai'::text, 'Gemini'::text, 'gemini'::text, 'subscription'::text, 20::numeric, 15::numeric),
  (21, 'ai'::text, 'GenSpark'::text, 'genspark'::text, 'subscription'::text, 15::numeric, 15::numeric),
  (22, 'ai'::text, 'Manus'::text, 'manus'::text, 'subscription'::text, 20::numeric, 15::numeric),
  (23, 'ai'::text, 'Higgsfield'::text, 'higgsfield'::text, 'subscription'::text, 15::numeric, 15::numeric),
  (24, 'subs'::text, 'ChatGPT'::text, 'chatgpt'::text, 'subscription'::text, 20::numeric, 15::numeric),
  (25, 'subs'::text, 'Netflix'::text, 'netflix'::text, 'subscription'::text, 19.99::numeric, 15::numeric),
  (26, 'subs'::text, 'Spotify'::text, 'spotify'::text, 'subscription'::text, 12.99::numeric, 15::numeric),
  (27, 'subs'::text, 'YouTube Premium'::text, 'youtube'::text, 'subscription'::text, 13.99::numeric, 15::numeric),
  (28, 'subs'::text, 'Apple One'::text, 'apple'::text, 'subscription'::text, 19.95::numeric, 15::numeric),
  (29, 'subs'::text, 'Disney+'::text, 'disneyplus'::text, 'subscription'::text, 15.99::numeric, 15::numeric),
  (30, 'subs'::text, 'Notion'::text, 'notion'::text, 'subscription'::text, 12::numeric, 15::numeric),
  (31, 'subs'::text, 'Figma'::text, 'figma'::text, 'subscription'::text, 15::numeric, 15::numeric),
  (32, 'subs'::text, 'Adobe Creative Cloud'::text, 'adobe'::text, 'subscription'::text, 54.99::numeric, 15::numeric),
  (33, 'subs'::text, 'Zoom'::text, 'zoom'::text, 'subscription'::text, 15.99::numeric, 15::numeric),
  (34, 'subs'::text, 'Slack'::text, 'slack'::text, 'subscription'::text, 8.75::numeric, 15::numeric),
  (35, 'subs'::text, 'Discord Nitro'::text, 'discord'::text, 'subscription'::text, 9.99::numeric, 15::numeric),
  (36, 'subs'::text, 'Google One'::text, 'google_one'::text, 'subscription'::text, 9.99::numeric, 15::numeric),
  (37, 'subs'::text, 'Dropbox'::text, 'dropbox'::text, 'subscription'::text, 11.99::numeric, 15::numeric),
  (38, 'subs'::text, 'Canva Pro'::text, 'canva_pro'::text, 'subscription'::text, 14.99::numeric, 15::numeric),
  (39, 'subs'::text, 'Miro'::text, 'miro'::text, 'subscription'::text, 10::numeric, 15::numeric),
  (40, 'subs'::text, 'Trello'::text, 'trello'::text, 'subscription'::text, 6::numeric, 15::numeric),
  (41, 'subs'::text, 'NordVPN'::text, 'nordvpn'::text, 'subscription'::text, 12.99::numeric, 15::numeric),
  (42, 'subs'::text, 'ExpressVPN'::text, 'expressvpn'::text, 'subscription'::text, 12.95::numeric, 15::numeric),
  (43, 'subs'::text, 'Amazon Prime'::text, 'amazon_prime'::text, 'subscription'::text, 14.99::numeric, 15::numeric),
  (44, 'subs'::text, 'SoundCloud'::text, 'soundcloud'::text, 'subscription'::text, 9.99::numeric, 15::numeric),
  (45, 'subs'::text, 'Patreon'::text, 'patreon'::text, 'subscription'::text, 0::numeric, 15::numeric),
  (46, 'subs'::text, 'Tinder'::text, 'tinder'::text, 'subscription'::text, 14.99::numeric, 15::numeric),
  (47, 'subs'::text, 'OnlyFans'::text, 'onlyfans'::text, 'subscription'::text, 0::numeric, 15::numeric),
  (48, 'subs'::text, 'Badoo'::text, 'badoo'::text, 'subscription'::text, 9.99::numeric, 15::numeric),
  (49, 'subs'::text, 'GitHub'::text, 'github'::text, 'subscription'::text, 10::numeric, 15::numeric),
  (50, 'subs'::text, 'Deezer'::text, 'deezer'::text, 'subscription'::text, 11.99::numeric, 15::numeric),
  (51, 'subs'::text, 'Tidal'::text, 'tidal'::text, 'subscription'::text, 10.99::numeric, 15::numeric),
  (52, 'travel'::text, 'Booking.com'::text, 'booking_com'::text, 'one_off'::text, 0::numeric, 15::numeric),
  (53, 'travel'::text, 'Airbnb'::text, 'airbnb'::text, 'one_off'::text, 0::numeric, 15::numeric),
  (54, 'travel'::text, 'Expedia'::text, 'expedia'::text, 'one_off'::text, 0::numeric, 15::numeric),
  (55, 'travel'::text, 'Hotels.com'::text, 'hotels_com'::text, 'one_off'::text, 0::numeric, 15::numeric),
  (56, 'travel'::text, 'Emirates'::text, 'emirates'::text, 'one_off'::text, 0::numeric, 15::numeric),
  (57, 'travel'::text, 'Turkish Airlines'::text, 'turkish_airlines'::text, 'one_off'::text, 0::numeric, 15::numeric),
  (58, 'travel'::text, 'Lufthansa'::text, 'lufthansa'::text, 'one_off'::text, 0::numeric, 15::numeric),
  (59, 'travel'::text, 'Air France'::text, 'air_france'::text, 'one_off'::text, 0::numeric, 15::numeric),
  (60, 'travel'::text, 'British Airways'::text, 'british_airways'::text, 'one_off'::text, 0::numeric, 15::numeric),
  (61, 'travel'::text, 'Ryanair'::text, 'ryanair'::text, 'one_off'::text, 0::numeric, 15::numeric),
  (62, 'travel'::text, 'Klook'::text, 'klook'::text, 'one_off'::text, 0::numeric, 15::numeric),
  (63, 'travel'::text, 'Trip.com'::text, 'trip_com'::text, 'one_off'::text, 0::numeric, 15::numeric),
  (64, 'market'::text, 'Steam'::text, 'steam'::text, 'topup'::text, 50::numeric, 15::numeric),
  (65, 'market'::text, 'Epic Games Store'::text, 'epic_games'::text, 'topup'::text, 60::numeric, 15::numeric),
  (66, 'market'::text, 'PlayStation Store'::text, 'playstation'::text, 'topup'::text, 60::numeric, 15::numeric),
  (67, 'market'::text, 'GOG'::text, 'gog'::text, 'one_off'::text, 40::numeric, 15::numeric),
  (68, 'market'::text, 'Ubisoft Connect'::text, 'ubisoft'::text, 'one_off'::text, 60::numeric, 15::numeric),
  (69, 'market'::text, 'EA (Electronic Arts)'::text, 'ea'::text, 'one_off'::text, 60::numeric, 15::numeric),
  (70, 'market'::text, 'Roblox'::text, 'roblox'::text, 'topup'::text, 25::numeric, 15::numeric),
  (71, 'market'::text, 'Amazon'::text, 'amazon'::text, 'one_off'::text, 0::numeric, 15::numeric),
  (72, 'market'::text, 'eBay'::text, 'ebay'::text, 'one_off'::text, 0::numeric, 15::numeric),
  (73, 'market'::text, 'AliExpress'::text, 'aliexpress'::text, 'one_off'::text, 0::numeric, 15::numeric),
  (74, 'market'::text, 'Etsy'::text, 'etsy'::text, 'one_off'::text, 0::numeric, 15::numeric),
  (75, 'market'::text, 'G2A'::text, 'g2a'::text, 'one_off'::text, 0::numeric, 15::numeric),
  (76, 'market'::text, 'Humble Bundle'::text, 'humble_bundle'::text, 'one_off'::text, 15::numeric, 15::numeric),
  (77, 'transfers'::text, 'Alipay'::text, 'alipay'::text, 'topup'::text, 0::numeric, 15::numeric),
  (78, 'transfers'::text, 'Денежные переводы'::text, 'money_transfers'::text, 'transfer'::text, 0::numeric, 15::numeric),
  (79, 'business'::text, 'Wise'::text, 'wise'::text, 'other'::text, 0::numeric, 15::numeric),
  (80, 'business'::text, 'Payoneer'::text, 'payoneer'::text, 'other'::text, 0::numeric, 15::numeric),
  (81, 'business'::text, 'Upwork'::text, 'upwork'::text, 'other'::text, 0::numeric, 15::numeric),
  (82, 'business'::text, 'Shopify'::text, 'shopify'::text, 'other'::text, 39::numeric, 15::numeric),
  (83, 'business'::text, 'Fiverr'::text, 'fiverr'::text, 'other'::text, 0::numeric, 15::numeric),
  (84, 'business'::text, 'GitLab'::text, 'gitlab'::text, 'other'::text, 29::numeric, 15::numeric),
  (85, 'business'::text, 'Vercel'::text, 'vercel'::text, 'other'::text, 20::numeric, 15::numeric),
  (86, 'business'::text, 'Cloudflare'::text, 'cloudflare'::text, 'other'::text, 20::numeric, 15::numeric),
  (87, 'business'::text, 'DigitalOcean'::text, 'digitalocean'::text, 'other'::text, 12::numeric, 15::numeric),
  (88, 'business'::text, 'Docker'::text, 'docker'::text, 'other'::text, 9::numeric, 15::numeric),
  (89, 'business'::text, 'Kubernetes'::text, 'kubernetes'::text, 'other'::text, 0::numeric, 15::numeric),
  (90, 'business'::text, 'Jira'::text, 'jira'::text, 'other'::text, 8.15::numeric, 15::numeric),
  (91, 'business'::text, 'Asana'::text, 'asana'::text, 'other'::text, 10.99::numeric, 15::numeric),
  (92, 'business'::text, 'Linear'::text, 'linear'::text, 'other'::text, 8::numeric, 15::numeric),
  (93, 'business'::text, 'Stripe'::text, 'stripe'::text, 'other'::text, 0::numeric, 15::numeric)
) AS v(ord, cat_slug, name, catalog_key, line_type, cost_usd, markup) ON c.slug = v.cat_slug
ON CONFLICT (catalog_key) DO UPDATE SET
  name = EXCLUDED.name,
  category_id = EXCLUDED.category_id,
  line_type = EXCLUDED.line_type,
  cost_usd = EXCLUDED.cost_usd,
  updated_at = now();
